// Code generated by protoc-gen-go. DO NOT EDIT.
// source: encryption.proto

package chat

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Bundle struct {
	Identity             []byte   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	SignedPreKey         []byte   `protobuf:"bytes,2,opt,name=signed_pre_key,json=signedPreKey,proto3" json:"signed_pre_key,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bundle) Reset()         { *m = Bundle{} }
func (m *Bundle) String() string { return proto.CompactTextString(m) }
func (*Bundle) ProtoMessage()    {}
func (*Bundle) Descriptor() ([]byte, []int) {
	return fileDescriptor_encryption_19a06346e08dc1c1, []int{0}
}
func (m *Bundle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bundle.Unmarshal(m, b)
}
func (m *Bundle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bundle.Marshal(b, m, deterministic)
}
func (dst *Bundle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bundle.Merge(dst, src)
}
func (m *Bundle) XXX_Size() int {
	return xxx_messageInfo_Bundle.Size(m)
}
func (m *Bundle) XXX_DiscardUnknown() {
	xxx_messageInfo_Bundle.DiscardUnknown(m)
}

var xxx_messageInfo_Bundle proto.InternalMessageInfo

func (m *Bundle) GetIdentity() []byte {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *Bundle) GetSignedPreKey() []byte {
	if m != nil {
		return m.SignedPreKey
	}
	return nil
}

func (m *Bundle) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type BundleContainer struct {
	Bundle               *Bundle  `protobuf:"bytes,1,opt,name=bundle,proto3" json:"bundle,omitempty"`
	PrivateSignedPreKey  []byte   `protobuf:"bytes,2,opt,name=private_signed_pre_key,json=privateSignedPreKey,proto3" json:"private_signed_pre_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BundleContainer) Reset()         { *m = BundleContainer{} }
func (m *BundleContainer) String() string { return proto.CompactTextString(m) }
func (*BundleContainer) ProtoMessage()    {}
func (*BundleContainer) Descriptor() ([]byte, []int) {
	return fileDescriptor_encryption_19a06346e08dc1c1, []int{1}
}
func (m *BundleContainer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BundleContainer.Unmarshal(m, b)
}
func (m *BundleContainer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BundleContainer.Marshal(b, m, deterministic)
}
func (dst *BundleContainer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BundleContainer.Merge(dst, src)
}
func (m *BundleContainer) XXX_Size() int {
	return xxx_messageInfo_BundleContainer.Size(m)
}
func (m *BundleContainer) XXX_DiscardUnknown() {
	xxx_messageInfo_BundleContainer.DiscardUnknown(m)
}

var xxx_messageInfo_BundleContainer proto.InternalMessageInfo

func (m *BundleContainer) GetBundle() *Bundle {
	if m != nil {
		return m.Bundle
	}
	return nil
}

func (m *BundleContainer) GetPrivateSignedPreKey() []byte {
	if m != nil {
		return m.PrivateSignedPreKey
	}
	return nil
}

type DirectMessageProtocol struct {
	// Which ephemeral key has been used
	//
	// Types that are valid to be assigned to EphemeralKey:
	//	*DirectMessageProtocol_BundleKey
	//	*DirectMessageProtocol_DhKey
	//	*DirectMessageProtocol_SymKey
	EphemeralKey isDirectMessageProtocol_EphemeralKey `protobuf_oneof:"ephemeral_key"`
	// The bundle used in case of x3dh
	BundleId             []byte   `protobuf:"bytes,4,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	Payload              []byte   `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DirectMessageProtocol) Reset()         { *m = DirectMessageProtocol{} }
func (m *DirectMessageProtocol) String() string { return proto.CompactTextString(m) }
func (*DirectMessageProtocol) ProtoMessage()    {}
func (*DirectMessageProtocol) Descriptor() ([]byte, []int) {
	return fileDescriptor_encryption_19a06346e08dc1c1, []int{2}
}
func (m *DirectMessageProtocol) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectMessageProtocol.Unmarshal(m, b)
}
func (m *DirectMessageProtocol) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectMessageProtocol.Marshal(b, m, deterministic)
}
func (dst *DirectMessageProtocol) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectMessageProtocol.Merge(dst, src)
}
func (m *DirectMessageProtocol) XXX_Size() int {
	return xxx_messageInfo_DirectMessageProtocol.Size(m)
}
func (m *DirectMessageProtocol) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectMessageProtocol.DiscardUnknown(m)
}

var xxx_messageInfo_DirectMessageProtocol proto.InternalMessageInfo

type isDirectMessageProtocol_EphemeralKey interface {
	isDirectMessageProtocol_EphemeralKey()
}

type DirectMessageProtocol_BundleKey struct {
	BundleKey []byte `protobuf:"bytes,1,opt,name=bundle_key,json=bundleKey,proto3,oneof"`
}
type DirectMessageProtocol_DhKey struct {
	DhKey []byte `protobuf:"bytes,2,opt,name=dh_key,json=dhKey,proto3,oneof"`
}
type DirectMessageProtocol_SymKey struct {
	SymKey []byte `protobuf:"bytes,3,opt,name=sym_key,json=symKey,proto3,oneof"`
}

func (*DirectMessageProtocol_BundleKey) isDirectMessageProtocol_EphemeralKey() {}
func (*DirectMessageProtocol_DhKey) isDirectMessageProtocol_EphemeralKey()     {}
func (*DirectMessageProtocol_SymKey) isDirectMessageProtocol_EphemeralKey()    {}

func (m *DirectMessageProtocol) GetEphemeralKey() isDirectMessageProtocol_EphemeralKey {
	if m != nil {
		return m.EphemeralKey
	}
	return nil
}

func (m *DirectMessageProtocol) GetBundleKey() []byte {
	if x, ok := m.GetEphemeralKey().(*DirectMessageProtocol_BundleKey); ok {
		return x.BundleKey
	}
	return nil
}

func (m *DirectMessageProtocol) GetDhKey() []byte {
	if x, ok := m.GetEphemeralKey().(*DirectMessageProtocol_DhKey); ok {
		return x.DhKey
	}
	return nil
}

func (m *DirectMessageProtocol) GetSymKey() []byte {
	if x, ok := m.GetEphemeralKey().(*DirectMessageProtocol_SymKey); ok {
		return x.SymKey
	}
	return nil
}

func (m *DirectMessageProtocol) GetBundleId() []byte {
	if m != nil {
		return m.BundleId
	}
	return nil
}

func (m *DirectMessageProtocol) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*DirectMessageProtocol) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _DirectMessageProtocol_OneofMarshaler, _DirectMessageProtocol_OneofUnmarshaler, _DirectMessageProtocol_OneofSizer, []interface{}{
		(*DirectMessageProtocol_BundleKey)(nil),
		(*DirectMessageProtocol_DhKey)(nil),
		(*DirectMessageProtocol_SymKey)(nil),
	}
}

func _DirectMessageProtocol_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*DirectMessageProtocol)
	// ephemeral_key
	switch x := m.EphemeralKey.(type) {
	case *DirectMessageProtocol_BundleKey:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.BundleKey)
	case *DirectMessageProtocol_DhKey:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.DhKey)
	case *DirectMessageProtocol_SymKey:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.SymKey)
	case nil:
	default:
		return fmt.Errorf("DirectMessageProtocol.EphemeralKey has unexpected type %T", x)
	}
	return nil
}

func _DirectMessageProtocol_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*DirectMessageProtocol)
	switch tag {
	case 1: // ephemeral_key.bundle_key
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.EphemeralKey = &DirectMessageProtocol_BundleKey{x}
		return true, err
	case 2: // ephemeral_key.dh_key
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.EphemeralKey = &DirectMessageProtocol_DhKey{x}
		return true, err
	case 3: // ephemeral_key.sym_key
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.EphemeralKey = &DirectMessageProtocol_SymKey{x}
		return true, err
	default:
		return false, nil
	}
}

func _DirectMessageProtocol_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*DirectMessageProtocol)
	// ephemeral_key
	switch x := m.EphemeralKey.(type) {
	case *DirectMessageProtocol_BundleKey:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.BundleKey)))
		n += len(x.BundleKey)
	case *DirectMessageProtocol_DhKey:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.DhKey)))
		n += len(x.DhKey)
	case *DirectMessageProtocol_SymKey:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.SymKey)))
		n += len(x.SymKey)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ProtocolMessage struct {
	Bundle *Bundle `protobuf:"bytes,1,opt,name=bundle,proto3" json:"bundle,omitempty"`
	// Types that are valid to be assigned to MessageType:
	//	*ProtocolMessage_DirectMessage
	//	*ProtocolMessage_PublicMessage
	MessageType          isProtocolMessage_MessageType `protobuf_oneof:"message_type"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ProtocolMessage) Reset()         { *m = ProtocolMessage{} }
func (m *ProtocolMessage) String() string { return proto.CompactTextString(m) }
func (*ProtocolMessage) ProtoMessage()    {}
func (*ProtocolMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_encryption_19a06346e08dc1c1, []int{3}
}
func (m *ProtocolMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtocolMessage.Unmarshal(m, b)
}
func (m *ProtocolMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtocolMessage.Marshal(b, m, deterministic)
}
func (dst *ProtocolMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtocolMessage.Merge(dst, src)
}
func (m *ProtocolMessage) XXX_Size() int {
	return xxx_messageInfo_ProtocolMessage.Size(m)
}
func (m *ProtocolMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtocolMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ProtocolMessage proto.InternalMessageInfo

type isProtocolMessage_MessageType interface {
	isProtocolMessage_MessageType()
}

type ProtocolMessage_DirectMessage struct {
	DirectMessage *DirectMessageProtocol `protobuf:"bytes,101,opt,name=direct_message,json=directMessage,proto3,oneof"`
}
type ProtocolMessage_PublicMessage struct {
	PublicMessage []byte `protobuf:"bytes,102,opt,name=public_message,json=publicMessage,proto3,oneof"`
}

func (*ProtocolMessage_DirectMessage) isProtocolMessage_MessageType() {}
func (*ProtocolMessage_PublicMessage) isProtocolMessage_MessageType() {}

func (m *ProtocolMessage) GetMessageType() isProtocolMessage_MessageType {
	if m != nil {
		return m.MessageType
	}
	return nil
}

func (m *ProtocolMessage) GetBundle() *Bundle {
	if m != nil {
		return m.Bundle
	}
	return nil
}

func (m *ProtocolMessage) GetDirectMessage() *DirectMessageProtocol {
	if x, ok := m.GetMessageType().(*ProtocolMessage_DirectMessage); ok {
		return x.DirectMessage
	}
	return nil
}

func (m *ProtocolMessage) GetPublicMessage() []byte {
	if x, ok := m.GetMessageType().(*ProtocolMessage_PublicMessage); ok {
		return x.PublicMessage
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ProtocolMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ProtocolMessage_OneofMarshaler, _ProtocolMessage_OneofUnmarshaler, _ProtocolMessage_OneofSizer, []interface{}{
		(*ProtocolMessage_DirectMessage)(nil),
		(*ProtocolMessage_PublicMessage)(nil),
	}
}

func _ProtocolMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ProtocolMessage)
	// message_type
	switch x := m.MessageType.(type) {
	case *ProtocolMessage_DirectMessage:
		b.EncodeVarint(101<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DirectMessage); err != nil {
			return err
		}
	case *ProtocolMessage_PublicMessage:
		b.EncodeVarint(102<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.PublicMessage)
	case nil:
	default:
		return fmt.Errorf("ProtocolMessage.MessageType has unexpected type %T", x)
	}
	return nil
}

func _ProtocolMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ProtocolMessage)
	switch tag {
	case 101: // message_type.direct_message
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DirectMessageProtocol)
		err := b.DecodeMessage(msg)
		m.MessageType = &ProtocolMessage_DirectMessage{msg}
		return true, err
	case 102: // message_type.public_message
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.MessageType = &ProtocolMessage_PublicMessage{x}
		return true, err
	default:
		return false, nil
	}
}

func _ProtocolMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ProtocolMessage)
	// message_type
	switch x := m.MessageType.(type) {
	case *ProtocolMessage_DirectMessage:
		s := proto.Size(x.DirectMessage)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ProtocolMessage_PublicMessage:
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(len(x.PublicMessage)))
		n += len(x.PublicMessage)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Bundle)(nil), "chat.Bundle")
	proto.RegisterType((*BundleContainer)(nil), "chat.BundleContainer")
	proto.RegisterType((*DirectMessageProtocol)(nil), "chat.DirectMessageProtocol")
	proto.RegisterType((*ProtocolMessage)(nil), "chat.ProtocolMessage")
}

func init() { proto.RegisterFile("encryption.proto", fileDescriptor_encryption_19a06346e08dc1c1) }

var fileDescriptor_encryption_19a06346e08dc1c1 = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x6f, 0xe2, 0x30,
	0x14, 0x24, 0x0b, 0x84, 0xe5, 0x6d, 0x08, 0x2b, 0xaf, 0x76, 0x37, 0x2d, 0x95, 0x5a, 0x45, 0x48,
	0xed, 0x89, 0x43, 0xf9, 0x07, 0x94, 0x03, 0x55, 0x55, 0x09, 0xa5, 0x3f, 0x20, 0x32, 0xf1, 0x2b,
	0xb1, 0x9a, 0x0f, 0xcb, 0x31, 0x95, 0xfc, 0xbf, 0xaa, 0xfe, 0xbe, 0x2a, 0xb6, 0xf9, 0x38, 0x70,
	0xe8, 0xf1, 0xcd, 0x8c, 0xe7, 0xcd, 0x3c, 0x19, 0x7e, 0x63, 0x95, 0x49, 0x2d, 0x14, 0xaf, 0xab,
	0x99, 0x90, 0xb5, 0xaa, 0x49, 0x2f, 0xcb, 0xa9, 0x8a, 0x73, 0xf0, 0x17, 0xbb, 0x8a, 0x15, 0x48,
	0x2e, 0xe1, 0x27, 0x67, 0x58, 0x29, 0xae, 0x74, 0xe4, 0xdd, 0x78, 0x77, 0x41, 0x72, 0x98, 0xc9,
	0x14, 0xc2, 0x86, 0x6f, 0x2b, 0x64, 0xa9, 0x90, 0x98, 0xbe, 0xa1, 0x8e, 0x7e, 0x18, 0x45, 0x60,
	0xd1, 0xb5, 0xc4, 0x27, 0xd4, 0xe4, 0x0a, 0x86, 0xed, 0x4c, 0xd5, 0x4e, 0x62, 0xd4, 0x35, 0x82,
	0x23, 0x10, 0x17, 0x30, 0xb6, 0x9b, 0x1e, 0xea, 0x4a, 0x51, 0x5e, 0xa1, 0x24, 0x53, 0xf0, 0x37,
	0x06, 0x32, 0x0b, 0x7f, 0xdd, 0x07, 0xb3, 0x36, 0xd3, 0xcc, 0xca, 0x12, 0xc7, 0x91, 0x39, 0xfc,
	0x13, 0x92, 0xbf, 0x53, 0x85, 0xe9, 0xd9, 0x10, 0x7f, 0x1c, 0xfb, 0x72, 0x92, 0x25, 0xfe, 0xf0,
	0xe0, 0xef, 0x92, 0x4b, 0xcc, 0xd4, 0x33, 0x36, 0x0d, 0xdd, 0xe2, 0xba, 0x2d, 0x9d, 0xd5, 0x05,
	0xb9, 0x06, 0xb0, 0xc6, 0xc6, 0xc2, 0x34, 0x5d, 0x75, 0x92, 0xa1, 0xc5, 0xda, 0x1a, 0xff, 0xc1,
	0x67, 0xf9, 0xd1, 0x7f, 0xd5, 0x49, 0xfa, 0x2c, 0x6f, 0x89, 0x0b, 0x18, 0x34, 0xba, 0x34, 0x4c,
	0xd7, 0x31, 0x7e, 0xa3, 0xcb, 0x96, 0x9a, 0x80, 0x33, 0x48, 0x39, 0x8b, 0x7a, 0xf6, 0x7a, 0x16,
	0x78, 0x64, 0x24, 0x82, 0x81, 0xa0, 0xba, 0xa8, 0x29, 0x8b, 0xfa, 0x86, 0xda, 0x8f, 0x8b, 0x31,
	0x8c, 0x50, 0xe4, 0x58, 0xa2, 0xa4, 0x45, 0xeb, 0x1b, 0x7f, 0x7a, 0x30, 0xde, 0x27, 0x75, 0xc1,
	0xbf, 0x79, 0xa5, 0x25, 0x84, 0xcc, 0xf4, 0x4d, 0x4b, 0xfb, 0x2e, 0x42, 0xa3, 0x9e, 0x58, 0xf5,
	0xd9, 0x5b, 0xac, 0x3a, 0xc9, 0x88, 0x9d, 0x12, 0xe4, 0x16, 0x42, 0xb1, 0xdb, 0x14, 0x3c, 0x3b,
	0xb8, 0xbc, 0xba, 0xa6, 0x23, 0x8b, 0x3b, 0xe1, 0x22, 0x84, 0xc0, 0x29, 0x52, 0xa5, 0x05, 0x6e,
	0x7c, 0xf3, 0xa9, 0xe6, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x00, 0x12, 0xf3, 0x83, 0x68, 0x02,
	0x00, 0x00,
}
